// Code generated by MockGen. DO NOT EDIT.
// Source: internal/common/http.go
//
// Generated by this command:
//
//	mockgen -source=internal/common/http.go -destination=internal/common/mock_http.go -package=common LarkClientInterface
//

// Package common is a generated GoMock package.
package common
